--TEST--
openswoole_backward_compat: SWOOLE_WEBSOCKET_* constant aliases
--SKIPIF--
<?php require __DIR__ . '/../include/skipif.inc'; ?>
--FILE--
<?php declare(strict_types = 1);
require __DIR__ . '/../include/bootstrap.php';

// Opcodes
Assert::assert(defined('SWOOLE_WEBSOCKET_OPCODE_CONTINUATION'));
Assert::assert(defined('SWOOLE_WEBSOCKET_OPCODE_TEXT'));
Assert::assert(defined('SWOOLE_WEBSOCKET_OPCODE_BINARY'));
Assert::assert(defined('SWOOLE_WEBSOCKET_OPCODE_CLOSE'));
Assert::assert(defined('SWOOLE_WEBSOCKET_OPCODE_PING'));
Assert::assert(defined('SWOOLE_WEBSOCKET_OPCODE_PONG'));
Assert::same(SWOOLE_WEBSOCKET_OPCODE_TEXT, OPENSWOOLE_WEBSOCKET_OPCODE_TEXT);
Assert::same(SWOOLE_WEBSOCKET_OPCODE_BINARY, OPENSWOOLE_WEBSOCKET_OPCODE_BINARY);
Assert::same(SWOOLE_WEBSOCKET_OPCODE_PING, OPENSWOOLE_WEBSOCKET_OPCODE_PING);
Assert::same(SWOOLE_WEBSOCKET_OPCODE_PONG, OPENSWOOLE_WEBSOCKET_OPCODE_PONG);

// Close codes
Assert::assert(defined('SWOOLE_WEBSOCKET_CLOSE_NORMAL'));
Assert::assert(defined('SWOOLE_WEBSOCKET_CLOSE_GOING_AWAY'));
Assert::assert(defined('SWOOLE_WEBSOCKET_CLOSE_PROTOCOL_ERROR'));
Assert::assert(defined('SWOOLE_WEBSOCKET_CLOSE_DATA_ERROR'));
Assert::assert(defined('SWOOLE_WEBSOCKET_CLOSE_ABNORMAL'));
Assert::assert(defined('SWOOLE_WEBSOCKET_CLOSE_MESSAGE_ERROR'));
Assert::assert(defined('SWOOLE_WEBSOCKET_CLOSE_TLS'));
Assert::same(SWOOLE_WEBSOCKET_CLOSE_NORMAL, OPENSWOOLE_WEBSOCKET_CLOSE_NORMAL);
Assert::same(SWOOLE_WEBSOCKET_CLOSE_GOING_AWAY, OPENSWOOLE_WEBSOCKET_CLOSE_GOING_AWAY);
Assert::same(SWOOLE_WEBSOCKET_CLOSE_PROTOCOL_ERROR, OPENSWOOLE_WEBSOCKET_CLOSE_PROTOCOL_ERROR);
Assert::same(SWOOLE_WEBSOCKET_CLOSE_ABNORMAL, OPENSWOOLE_WEBSOCKET_CLOSE_ABNORMAL);

// Status
Assert::assert(defined('SWOOLE_WEBSOCKET_STATUS_CONNECTION'));
Assert::assert(defined('SWOOLE_WEBSOCKET_STATUS_HANDSHAKE'));
Assert::assert(defined('SWOOLE_WEBSOCKET_STATUS_ACTIVE'));
Assert::assert(defined('SWOOLE_WEBSOCKET_STATUS_CLOSING'));
Assert::same(SWOOLE_WEBSOCKET_STATUS_ACTIVE, OPENSWOOLE_WEBSOCKET_STATUS_ACTIVE);

// Flags
Assert::assert(defined('SWOOLE_WEBSOCKET_FLAG_FIN'));
Assert::assert(defined('SWOOLE_WEBSOCKET_FLAG_RSV1'));
Assert::assert(defined('SWOOLE_WEBSOCKET_FLAG_RSV2'));
Assert::assert(defined('SWOOLE_WEBSOCKET_FLAG_RSV3'));
Assert::assert(defined('SWOOLE_WEBSOCKET_FLAG_MASK'));
Assert::assert(defined('SWOOLE_WEBSOCKET_FLAG_COMPRESS'));
Assert::same(SWOOLE_WEBSOCKET_FLAG_FIN, OPENSWOOLE_WEBSOCKET_FLAG_FIN);
Assert::same(SWOOLE_WEBSOCKET_FLAG_COMPRESS, OPENSWOOLE_WEBSOCKET_FLAG_COMPRESS);

echo "PASSED\n";
?>
--EXPECT--
PASSED
